name: Publish Findream-ui To Npm

on:
  push:
    branches: ['publish']

jobs:
  publish:
    name: 'publish npm'
    runs-on: 'ubuntu-latest'
    environment: npm

    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@v2.1.0
        with:
          version: 6.31.0

      - name: 'Install modules'
        run: pnpm install

      - name: 'Build'
        run: npm run build

      - name: 'Publish to the npm registry'
        uses: primer/publish@3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        with:
          default_branch: 'publish'
          #dir: "packages/smarty-ui-vite"
